### ISSUE TITLE
Returns wrong uri if hostname starts with "amqp"

### ISSUE THREAD

**Issue by pawelotto** [nfantone/amqp-uri#31]
It happened that my remote server name starts with **amqp**.example.com and in this situation the module returns WRONG url.

**Comment by nfantone** [comment]
Good catch and thanks for the PR!

**Comment by pawelotto** [comment]
Sure no problems, mate, sorry for the unnecessary escapes though, will correct this and commit on Monday. Have a good one!

**Comment by nfantone** [comment]
I had some time on my hands so I revamped a few things on the repo - hopefully it won't make your rebasing too problematic. Or open a new PR if that's easier for you.
